import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar.client";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
          <main className="reletive overflow-hidden">
            {children}
          </main>
        <Footer/>
      </body>
    </html>
  );
}
